name: Portfolio Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Move build files to public directory
        run: |
          rm -rf public/*
          cp -r dist/* public/
